//whole list
export const PRODUCT_LIST_REQ = 'PRODUCT_LIST_REQ'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

//one product
export const PRODUCT_DETAIL_REQ = 'PRODUCT_DETAIL_REQ'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'